In [ ]:
# array는 배열을 의미
# 1차원 array는 벡터(세로방향), 2차원 array는 matrix, 3차원 array는 매트릭스를 위로 쌓은 큐브형태
# numpy에게 데이터를 제공하려면 array 형태로써 제공해줘야 함.


In [1]:
import numpy as np

#numpy를 사용하기 위해 array 형태로 만들기
data1 = [1,2,3,4,5] #이건 array가 아니라 리스트. 리스트 안에는 서로 다른 유형들이 들어갈 수 있다 (지금은 전부 int로써 같은 경우).
# ****************하지만 array 안에는 같은 유형들만 들어가야 한다. 전부 숫자이거나, 전부 날짜이거나..
array1 = np.array(data1) #데이터를 array로 바꾸는 함수. 어라 array 출력값에는 리스트의 출력값과 달리 컴마가 없네
print(array1)

# array 의 크기와 형태 확인
array1.shape #.shape를 사용하면 출력값이 (a,b)형태이다. 이는 a행 b열의 array를 의미한다.
# 만약 출력값이 (5,)라면 이는 1차원 array이자, 매트릭스가 아니라 5차원 벡터라는 의미이다.

[1 2 3 4 5]


(5,)

In [3]:
#numpy를 사용하기 위해 array 형태로 만들기
data2 = [1 , 2 , 3 , 4 , 5.5] #리스트 안에 서로 다른 유형이 들어간 경우.(int 4개와 float 1개)
array2 = np.array(data2) #이럴 경우에 array처리해버리면 전부 float데이터로 바뀜 -> 데이터의 변질 ㅠㅠ
print(array2)

# array 의 크기와 형태 확인
array2.shape

[1.  2.  3.  4.  5.5]


(5,)

In [4]:
#numpy를 사용하기 위해 array 형태로 만들기
data3 = [1 , 2 , 3 , 4 , '새우깡'] #새우깡이라는 str이 섞여있음
array3 = np.array(data3) #이럴 경우에 array 처리해버리면 전부 str으로 변질됨 ㅠㅠ
print(array3) #str 변질여부는 출력값을 보면 알 수 있음. 리스트 안의 int들이 출력값에선 전부 홑따옴표로 감싸져 있잖아.

# array 의 크기와 형태 확인
array3.shape

['1' '2' '3' '4' '새우깡']


(5,)

In [7]:
#arrary() 함수안에 리스트 바로 사용하기
#사실 이렇게 리스트 자체를 array에 넣는 건 안 함. 변수에 리스트틀 넣고, 어레이에 변수를 넣는 편이 리스트 수정에 더 쉽거든 ㅋ
array4 = np.array( [1,2,3,4,5])
print(array4)
array4.shape

[1 2 3 4 5]


(5,)

In [8]:
# 데이터 타입 확인하기
# 하나의 array에 들어있으면 데이터 타입이 다 똑같으니까
print('array1:',array1.dtype)
print('array2:',array2.dtype)
print('array3:',array3.dtype)
print('array4:',array4.dtype)

array1: int32
array2: float64
array3: <U11
array4: int32


In [48]:
#0으로 구성된 N차원 배열 생성
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
# 1 로 구성된 N차원 배열 생성
print(np.ones((3,4), dtype=np.int16))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [41]:
#arange( )함수 - 특정 범위 내에서 N만큼 연속적으로 차이나는 배열 생성
print(np.arange(10, 30, 5))
print(np.arange(10, 15))

[10 15 20 25]
[10 11 12 13 14]


In [48]:
#linespace( ) 함수 - 특정 범위 내에서 N등분하기
x = np.linspace(0, 99, 100) # 0~99까지 100등분
print(x)

x1 = np.linspace(0, 99, 4) # 0~99까지 4등분
print(x1)
#위 셀에서 arrange범위는 range범위 때처럼 종료항을 포함 안 시켰음.
#하지만 linespace에서는 종료항을 범위에 포함시키네.

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]
[ 0. 33. 66. 99.]


In [49]:

#************* 2차원의 array 생성하기






array5 = np.array( [ [1,2,3],[3,4,5],[5,6,7] ])
#리스트 안에 [1,2,3],[3,4,5],[5,6,7] 세 가지가 들어있음.
# 리스트 안에 리스트들을 넣으면 이렇게 되는구나
print(array5)

array5.shape

[[1 2 3]
 [3 4 5]
 [5 6 7]]


(3, 3)

In [63]:
#reshape( ) 함수를 사용하여 array의 차원을 변경하기
array_6=np.arange(12)
print(array_6)

#arange에서 시작점은 기본적으로 0, 인터벌은 기본적으로 1이다.
array6=np.arange(12).reshape(4,3) 
print(array6)
#애초에 n차원 어레이 출력형태가 []안에 행단위의[]들로 이뤄지구나

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [78]:
#reshape( ) 함수를 사용하여 array의 차원을 변경하기
array7=array6.reshape(2,6)
print(array7)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [64]:
#reshape( ) 함수를 사용하여 array의 차원을 변경하기
array_8=array6.reshape(-1,1)
print(array_8)

array8=array6.reshape(-11,3)
print(array8)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [56]:
# 참고 : reshape( ) 함수는 원본 데이터를 복사하여 복사본의 형태를 바꾸고
# resize( ) 함수는 원본의 데이터를 변경합니다.

In [85]:
# 2차원 array끼리 합치기 - vstack( ) / hstack( )
array1 = np.array([ [1,2],[3,4]])
print(array1)
# 리스트 안에 리스트들이 있는 꼴이니까 저렇게 나오구나

print()

array10 = np.array([ 1,2,3,4])
print(array10)
# 참고로 만약에 '리스트 안에 리스트들이 있는 것'이 아니라, 그냥 리스트만 있다면 이렇구나

print()

array2 = np.array([ [5,6],[7,8]])
print(array2)

print()

#vstack( ) 
print('-vstack:','\n',np.vstack((array1,array2)))

print()

#hstack( )
print('-hstack:''\n',np.hstack((array1,array2)))

[[1 2]
 [3 4]]

[1 2 3 4]

[[5 6]
 [7 8]]

-vstack: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

-hstack:
 [[1 2 5 6]
 [3 4 7 8]]


In [84]:
# 2개 이상의 리스트를 array 로 합치기
# "원하는 컬럼만 뽑아서 array를 만드는 게 column_stack"이라고 강사가 설명함.
# 왜 하필 이름이 '컬럼 스택'인지 이해하려 노력해본다면, 리스트에 array를 취해서 array로 변환을 하면 그건 그냥 1행인 array잖아.
# 그 array를 하나의 칼럼으로써 옆으로 차곡차곡 쌓는 의미 아닐까?

import numpy as np
name = np.array(['홍길동','일지매','전우치'])
# 그냥 리스트만 있는 거니까 저렇게.

loc = np.array(['서울','부산','대전'])
print(name)
print(loc)
print()

all_data = np.column_stack( (name,loc))
print(all_data)

['홍길동' '일지매' '전우치']
['서울' '부산' '대전']

[['홍길동' '서울']
 ['일지매' '부산']
 ['전우치' '대전']]


In [58]:
# array 산술연산하기
# 예제 데이터 생성하기

array1 = np.array( [ [1,2,3] , [4,5,6] ])
print(array1)
# 리스트 안에 리스트가 있는데 array를 거니까 어떻게 되겠어? 저렇게 되지.

print("\n")

array2 = np.array( [ [10,20,30] , [40,50,60] ])
print(array2)

[[1 2 3]
 [4 5 6]]


[[10 20 30]
 [40 50 60]]


In [59]:
# array 산술연산
# 1. 덧셈

array1 + array2

array([[11, 22, 33],
       [44, 55, 66]])

In [60]:
# array 산술연산
# 2. 뺄셈

array2 - array1

array([[ 9, 18, 27],
       [36, 45, 54]])

In [61]:
# array 산술연산
# 3. 각 원소끼리 곱셈

array1 * array2

array([[ 10,  40,  90],
       [160, 250, 360]])

In [64]:
# array 산술연산
# 4. 나눗셈

array2 / array1

array([[10., 10., 10.],
       [10., 10., 10.]])

In [131]:
a = np.array([2,3,4,5])
b = np.array([8,5,4])
ax,bx = np.ix_(a,b)

print(ax)
print('\n')
print(bx)
print('\n')
print(ax+bx)

[[2]
 [3]
 [4]
 [5]]


[[8 5 4]]


[[10  7  6]
 [11  8  7]
 [12  9  8]
 [13 10  9]]


In [136]:
a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])
ax,bx,cx = np.ix_(a,b,c)

print(ax)
print('\n')
print(bx)
print('\n')
print(cx)
print('\n')
print(ax+bx)
print('\n')
print(ax+bx+cx)

[[[2]]

 [[3]]

 [[4]]

 [[5]]]


[[[8]
  [5]
  [4]]]


[[[5 4 6 8 3]]]


[[[10]
  [ 7]
  [ 6]]

 [[11]
  [ 8]
  [ 7]]

 [[12]
  [ 9]
  [ 8]]

 [[13]
  [10]
  [ 9]]]


[[[15 14 16 18 13]
  [12 11 13 15 10]
  [11 10 12 14  9]]

 [[16 15 17 19 14]
  [13 12 14 16 11]
  [12 11 13 15 10]]

 [[17 16 18 20 15]
  [14 13 15 17 12]
  [13 12 14 16 11]]

 [[18 17 19 21 16]
  [15 14 16 18 13]
  [14 13 15 17 12]]]


In [95]:
# array 데이터 조회하기
# 1차원 array 조회하기
# range[1:]라면 
array1 = np.array([1,2,3,4,5])
print('전체값:' , array1)
print('1번째값:' , array1[0])
print('3번째값:' , array1[2])
print('2-4번째값:',array1[1:4])
print(arange[1:3])

전체값: [1 2 3 4 5]
1번째값: 1
3번째값: 3
2-4번째값: [2 3 4]


In [102]:
# array 데이터 조회하기
# 2차원 array 조회하기
array2 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
print(array2)
print('\n')
print(array2[2,2])
# 파이썬은 0행,0열부터 시작하니까 2행2열이 9임

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9


In [104]:
#numpy의 주요 분석 함수들


# 예제 데이터 만들기
array1 = np.random.randn(3,3) #정규분포를 따른 난수를 3*3행렬로 생성하는 함수
array1

array([[-0.72022259,  0.75590735, -0.52651463],
       [ 1.06094715, -0.05767979, -0.25960975],
       [-0.95329273,  0.48886513, -1.79968903]])

In [112]:
import numpy as np

# abs( ) 함수 - 절대값 계산하기
np.abs(array1)

array([[0.72022259, 0.75590735, 0.52651463],
       [1.06094715, 0.05767979, 0.25960975],
       [0.95329273, 0.48886513, 1.79968903]])

In [71]:
# square( ) 함수 - 제곱값 계산하기
np.square(array1)

array([[2.14236551e-03, 2.73109708e+00, 6.24562871e-01],
       [3.44608981e+00, 7.35511937e-01, 8.33847664e-01],
       [5.04785771e-01, 3.21139495e-01, 1.22690205e+00]])

In [72]:
# ceil( ) 함수 - 주어진 값보다 큰 가장 가까운 정수 찾기
np.ceil(array1)

array([[ 1.,  2.,  1.],
       [ 2., -0.,  1.],
       [ 1.,  1.,  2.]])

In [73]:
# floor( ) 함수 - 주어진 값보다 작은 가장 가까운 정수 찾기
np.floor(array1)

array([[ 0.,  1.,  0.],
       [ 1., -1.,  0.],
       [ 0.,  0.,  1.]])

In [113]:
#sum( ) 함수 - 합계 구하기
sum_ex = np.array([1,3,5,7,9])
print(sum_ex)
np.sum(sum_ex)

[1 3 5 7 9]


25

In [114]:
#cumsum( ) 함수 - 누적합계 구하기
np.cumsum(sum_ex)

array([ 1,  4,  9, 16, 25])

In [115]:
# isnan( ) 함수 - 주어진 값의 NaN 여부를 찾는 함수
# 여기서 NaN이란 Not a Number라는 뜻으로, 
print(array1)
np.isnan(array1)

[[-0.72022259  0.75590735 -0.52651463]
 [ 1.06094715 -0.05767979 -0.25960975]
 [-0.95329273  0.48886513 -1.79968903]]


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [77]:
#isinf( ) 함수 - 주어진 값의 무한대 여부를 찾는 함수
np.isinf(array1)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])